### ISSUE TITLE
Suggestion: disable for very long buffs?

### ISSUE THREAD

**Issue by fearkite** [sandervspl/BuffTimers#10]
Hey mate!

Awesome addon, does exactly what I want it to do! I just have one annoyance...

<img width="365" alt="image" src="https://user-images.githubusercontent.com/54443851/212540539-adb11c67-f74e-47b2-936f-a5cd223f44b0.png">

It'd be awesome if one could disable for more than what user has chosen, say, 1 day? It gets a bit long at times, especially when it comes to those contract buffs being 7 days! That's a lot of hours. Haha.

Thanks for your time and addon! :D 

<3

**Comment by sandervspl** [comment]
Hey @fearkite! Thanks for opening this issue. I have noticed this as well. I will likely change this behavior for very long buffs to simply show their most narrow duration. I am thinking of buffs longer than 3 hours should use this logic and add an option to change this threshold.

- If a buff is >3 hours long, it will show `Nh`. Example: `3h`, `6h`
- If a buff is >=24 hours long, it will show `Nd`. Example: `1d`, `7d`

I am not aware of buffs that are longer than 7 days. If there are any, I can look into displaying them as `1w`, `2w` for weeks. Let me know what you think!

**Comment by fearkite** [comment]
That sounds awesome to me mate! <3 

3 hours is perfect, even with Alchemist perks making Phials last longer.
Longer than 24 hours displaying as 'd' is great also! 

Thanks for replying so swiftly! Legend.

Have a good one mate and look froward to the update! :)

**Comment by sandervspl** [comment]
Fixed in c5711566f707ce8877990cdbfc5ae008a4eba73d. I will try to push an update today.
