### ISSUE TITLE
BuffButtonMixin and DebuffButtonMixin no longer exist on retail

### ISSUE THREAD

**Issue by ljosberinn** [sandervspl/BuffTimers#11]
https://github.com/sandervspl/BuffTimers/blob/master/BuffTimers.lua#L202

> 1x BuffTimers/BuffTimers.lua:202: Usage: hooksecurefunc([table,] "function", hookfunc)
> [string "=[C]"]: in function `hooksecurefunc'
> [string "@BuffTimers/BuffTimers.lua"]:202: in main chunk

![image](https://user-images.githubusercontent.com/29307652/214552844-98405141-bdb2-44d8-b418-dce5d1e7fe9f.png)

`BuffButtonMixin` is now `nil`

**Comment by sandervspl** [comment]
Thanks! Will try to push a fix today.

**Comment by ljosberinn** [comment]
https://github.com/tomrus88/BlizzardInterfaceCode/commit/997c50fbbc78d9156b95bae052ee692c279a6ac1#diff-38bb0f32292d52130b7f65076f4cdf062b1496e9ba9db9f8d51c8f32c96384a1

in this commit for 10.0.5, `BuffButtonMixin` was removed, and instead its now `AuraButtonMixin` apparently

**Comment by sandervspl** [comment]
~I possibly need to switch to using events instead of mixins, but I have no experience using that. It will take a bit more time than I expected to fix this.~

**Comment by sandervspl** [comment]
I have pushed an update (v1.9.2) to CurseForge that should fix this issue.

**Comment by ljosberinn** [comment]
cheers, looked into it earlier but didnt notice it was already solved 🎉
