### ISSUE TITLE
Duration Error

### ISSUE THREAD

**Issue by DerekJRasmussen** [sandervspl/BuffTimers#12]
Getting massive Lua errors after latest update in WoTLK Classic. 

The Lua Error stack trace is below. The error occurs on any buff with a timer.  

Message: Interface/AddOns/BuffTimers/BuffTimers.lua:164: attempt to index field 'Duration' (a nil value)
Time: Wed Jan 25 13:08:14 2023
Count: 4037
Stack: Interface/AddOns/BuffTimers/BuffTimers.lua:164: attempt to index field 'Duration' (a nil value)
[string "=[C]"]: ?
[string "@Interface/AddOns/BuffTimers/BuffTimers.lua"]:164: in function <Interface/AddOns/BuffTimers/BuffTimers.lua:162>
[string "=[C]"]: ?
[string "=[C]"]: in function `securecall'
[string "@Interface/FrameXML/BuffFrame.lua"]:260: in function <Interface/FrameXML/BuffFrame.lua:251>

Locals:

**Comment by sandervspl** [comment]
Should be fixed in the latest update! Sorry for that.
