### ISSUE TITLE
TWW Pre-Patch:  Error on Login

### ISSUE THREAD

**Issue by Bendder** [sandervspl/BuffTimers#20]
2x BuffTimers/Options.lua:47: attempt to call global 'InterfaceOptions_AddCategory' (a nil value)
[string "@BuffTimers/Options.lua"]:47: in main chunk

Locals:
_ = "BuffTimers"
ADDONSELF = <table> {
 L = <table> {
 }
}
L = <table> {
 BuffTimers = "BuffTimers"
}
defs = <table> {
}
changedcb = <table> {
}
f = Frame {
 name = "BuffTimers"
}
(*temporary) = nil
(*temporary) = Frame {
 name = "BuffTimers"
}
(*temporary) = "attempt to call global 'InterfaceOptions_AddCategory' (a nil value)"

**Comment by sandervspl** [comment]
Hi, thanks for the report. Fixed with https://github.com/sandervspl/BuffTimers/commit/6ff5330a6c762a298f13647d0176f3361d982323
