### ISSUE TITLE
Constant Lua Errors after new update

### ISSUE THREAD

**Issue by Jokaleth** [sandervspl/BuffTimers#7]
As the title says, after most recent update I am being constantly bombarded by this lua error

![image](https://user-images.githubusercontent.com/87456827/198680414-e5df918b-4e0c-4f4b-bcec-9e500b92e59f.png)

**Comment by ljosberinn** [comment]
should be fixed in latest release; just didnt get autoclosed

**Comment by sandervspl** [comment]
Fixed with #8
